name: Run Tests with Behave
on: [push]  # runs on push

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      # code heckout
      - name: Checkout repository
        uses: actions/checkout@v4

      # configures Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'  # version

      # install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Asegúrate de tener behave/allure-behave aquí

      # exec behave tests
      - name: Run Behave tests
        run: |
          behave features/ -f allure_behave.formatter:AllureFormatter -o allure-results -v

      # # allure results
      # - name: Upload Allure report
      #   uses: actions/upload-artifact@v3
      #   if: always()  # Sube reporte aunque fallen tests
      #   with:
      #     name: allure-report
      #     path: allure-results
